// Copy for the listing pages /recetas/, /guias/ and /carne/. Cards are generated from the collections.
export default [
 {id:'recetas',h1:'Recetas paraguayas y caseras',
  intro:['Sopa paraguaya, chipa guazú, mbeju, vori vori y los platos que se cocinan en casa todas las semanas. Cada receta trae cantidades que podés ajustar a tus porciones o a los kilos que vas a preparar, pasos con temporizador y un modo cocina que mantiene la pantalla encendida.','Elegí una categoría, buscá por ingrediente o dejá que te sugiramos qué cocinar hoy.'],
  categoryLabels:{paraguaya:'Paraguayas',pollo:'Con pollo',carne:'Con carne',fiesta:'Para fiestas',horno:'Al horno',rapida:'Rápidas',saludable:'Livianas',dulce:'Dulces',chipa:'Chipas'},
  sections:[{title:'Cómo usar las recetas',paragraphs:['Las cantidades de cada receta son una base. Si tu horno calienta más o tu queso es más salado, ajustá con el primer intento y anotá lo que te funcionó. En las recetas paraguayas que se preparan por kilo, como la chipa o la sopa, elegí los kilos arriba de los ingredientes y la lista se recalcula sola.','Tildá cada ingrediente cuando lo tengás sobre la mesada y cada paso cuando lo terminés: la página recuerda lo que marcaste en este dispositivo, así podés cerrar el navegador y volver.']}],
  faq:[['¿Las recetas sirven para cantidades grandes?','Sí. Podés multiplicar las porciones o los kilos desde el selector de cada receta. Para eventos de muchas personas, revisá también la capacidad de tu horno y de tus fuentes, porque los tiempos de cocción pueden cambiar.'],['¿Puedo imprimir una receta?','Sí. Usá el botón Imprimir de cada receta: la versión impresa deja solo los ingredientes y los pasos, sin menús ni botones.'],['¿Dónde compro los ingredientes paraguayos?','El queso Paraguay, el almidón y la harina de maíz se consiguen en supermercados, despensas y en el Mercado de Abasto de Asunción. En nuestra guía del Mercado de Abasto te contamos cómo comprar ahí.']]},
 {id:'guias',h1:'Guías para comprar, calcular y organizar comida',
  intro:['Respuestas concretas para decidir: cuánta comida calcular por persona, cuántos bocaditos pedir, cómo elegir el queso Paraguay o cómo aprovechar una visita al Mercado de Abasto.','Las cantidades que publicamos son estimaciones editoriales para orientarte; cada guía indica su fuente y la fecha de revisión.']},
 {id:'carne',h1:'Cortes de carne: qué es cada uno y cómo cocinarlo',
  intro:['Picaña, osobuco, peceto, vacío, bondiola: los cortes que más se buscan en Paraguay, explicados para elegir bien en la carnicería. Para cada uno te contamos de qué parte sale, cómo se cocina mejor y cuánto calcular por persona.','Si estás organizando un asado, empezá por la calculadora de carne por persona.'],
  sections:[{title:'Cómo elegir en la carnicería',paragraphs:['Pedí el corte por su nombre y preguntá de qué animal y de qué parte sale: los nombres cambian entre países y hasta entre carnicerías. Mirá el color, la grasa y el espesor antes de pagar, y pedí que te lo corten a la medida que necesitás para la receta.','Para la parrilla sirven los cortes con algo de grasa y cocción rápida; para la olla y el horno lento, los cortes con colágeno que se ablandan con tiempo, como el osobuco o la carnaza.']}]},
];
