export default [
  {id:'home'},
  {id:'catering',h1:'Catering para compartir tu próximo evento',image:1,
    intro:['Un almuerzo de trabajo, una fiesta familiar o una recepción necesitan servicios distintos. Elegí cómo querés recibir a tus invitados y contanos la fecha, la zona y cuántas personas esperás.','Te ayudamos a ordenar la consulta para que el proveedor pueda definir menú, montaje y atención. Revisamos tu solicitud y confirmamos disponibilidad en nuestro horario de atención.'],
    sections:[
      {title:'Elegí el formato que acompaña tu encuentro',cards:[['Bocaditos y recepción','Para encuentros de pie, combiná opciones saladas y dulces. Acordá la reposición y si necesitás bandejeo durante toda la reunión.'],['Buffet para compartir','Cada invitado elige su plato. Consultá cómo se organiza la fila, el mantenimiento de la temperatura y las alternativas del menú.'],['Menú servido a la mesa','Pensado para una comida con tiempos definidos. Coordiná la cantidad de mozos, el orden de salida y el espacio para trabajar.']]},
      {title:'Qué conviene dejar escrito',items:['Menú y cantidad de porciones acordadas.','Vajilla, mantelería y mobiliario incluidos o por separado.','Personal para montaje, atención y retiro.','Bebidas, hielo, traslado y horarios del servicio.','Condiciones para reservar, modificar o cancelar.']},
      {title:'Ideas para empezar la conversación',cards:[['Reunión de trabajo','Chipa, mini sándwiches, fruta y café. Indicá la duración de la pausa y si habrá otro servicio durante la jornada.'],['Celebración en casa','Asado con guarniciones, ensaladas y una opción sin carne. Contanos si hay parrilla, cocina o espacio cubierto.'],['Recepción social','Bocaditos fríos y calientes con un cierre dulce. Ajustá el menú según el horario y si reemplaza una comida.']]},
      {title:'Un presupuesto con el mismo alcance',paragraphs:['Depende del menú, la cantidad de personas y el servicio. Para comparar propuestas, pedí que detallen también traslado, personal, impuestos y lo que queda a tu cargo.']}
    ],faq:[['¿Puedo consultar sin tener el menú decidido?','Sí. Contanos el tipo de encuentro y cómo te gustaría servir la comida. El proveedor puede proponerte alternativas según el espacio y la fecha.'],['¿Hay un mínimo de invitados?','Cada servicio define su mínimo. Indicá la cantidad estimada para consultar opciones adecuadas a tu reunión.'],['¿Puedo pedir solo la comida?','Podés consultar entrega de comida o un servicio con atención. Aclaralo al inicio para que el presupuesto refleje lo que necesitás.'],['¿Las bebidas están incluidas?','No lo des por hecho. Pedí que la propuesta detalle bebidas, hielo, vasos y quién se ocupa de servir.'],['¿Cómo aviso que hay preferencias alimentarias?','Mencioná que necesitás opciones de menú. Los detalles se conversan directamente con el proveedor elegido antes de contratar.'],['¿Cómo reservo el servicio?','Cuando elijas una propuesta, acordá la reserva y las condiciones directamente con el proveedor que la ofrece.']],related:['occ-bodas','city-asuncion'],waMessage:'Hola, ¿me ayudás a elegir un catering para mi evento?'},
  {id:'occ-bodas',h1:'Catering para bodas: menús, formatos y presupuesto',image:7,
    intro:['La comida de tu casamiento tiene que acompañar la recepción, la cena y la fiesta. Antes de elegir platos, definí cuántos invitados esperás y qué momentos querés cubrir.','Contanos dónde celebrás, la fecha y el estilo de servicio que imaginás. Consultamos disponibilidad para que puedas conversar una propuesta con alcance claro.'],
    sections:[
      {title:'Cómo servir el menú de tu boda',cards:[['Recepción con bocaditos','Una bienvenida de pie permite recibir a los invitados mientras llegan. Coordiná el tiempo de bandejeo antes de pasar a la cena.'],['Buffet de casamiento','Ofrece variedad y un ritmo flexible. Revisá con el salón dónde ubicar las estaciones y cómo circularán los invitados.'],['Cena servida','Organizá entrada, principal y postre con tiempos acordados. El equipo de salón necesita conocer el programa de la celebración.']]},
      {title:'Qué incluye la propuesta de casamiento',items:['Recepción y cena detalladas por separado.','Vajilla, copas, cubiertos y mantelería.','Mozos, coordinación de salón y montaje.','Bebidas, barra o descorche, si corresponde.','Horario de retiro y tratamiento de sobrantes.']},
      {title:'Tres menús para imaginar tu celebración',cards:[['Clásico de salón','Recepción con chipa y bocaditos, carne con vegetales al horno y postre de frutas. Consultá una alternativa sin carne para el principal.'],['Cóctel y estaciones','Bocaditos de mandioca, mini sándwiches y una estación caliente, con dulces individuales al cierre. Pensado para una fiesta con movimiento.'],['Casamiento en quincho','Asado, sopa paraguaya, ensaladas de estación y un postre fresco. Confirmá parrilla, ventilación y un plan de lluvia con el lugar.']]},
      {title:'Qué cambia el costo de la boda',paragraphs:['La duración de la fiesta, la cantidad de invitados y los momentos de comida cambian el alcance del catering. Pedí que la cotización aclare prueba de menú, extras, traslado y condiciones de reserva.']}
    ],faq:[['¿Cuándo conviene consultar el catering de la boda?','Consultá cuando tengas una fecha tentativa y un lugar en vista. En fechas muy solicitadas conviene revisar disponibilidad antes de cerrar otros servicios.'],['¿Se puede hacer una degustación?','Preguntale al proveedor si ofrece prueba de menú, cómo se organiza y qué condiciones tiene. No todos los servicios la incluyen.'],['¿Qué pasa si cambia la cantidad de invitados?','Acordá por escrito hasta cuándo podés ajustar la cantidad y cómo se calcula el cambio en la propuesta.'],['¿El catering coordina con el salón?','Consultá quién coordina el ingreso, la cocina y el montaje. Compartí las reglas del salón antes de confirmar la reserva.'],['¿Podemos sumar una comida durante la fiesta?','Sí, podés pedir una propuesta para ese momento. Definí horario, porciones y personal necesario para que figure en el alcance.'],['¿Quién responde por el servicio contratado?','Contratás directamente con el proveedor de la boda. Revisá su identidad, las condiciones de seña y el procedimiento ante cambios o inconvenientes.']],related:['catering','city-asuncion'],waMessage:'Hola, estamos organizando nuestra boda. ¿Nos ayudás a consultar el catering?'},
  {id:'city-asuncion',h1:'Catering en Asunción, con la logística clara',image:29,
    intro:['Un evento en un salón, una oficina o un quincho de Asunción tiene necesidades distintas de acceso y montaje. Contanos el barrio y el tipo de espacio para consultar un servicio que pueda trabajar ahí.','En edificios, confirmá ascensor, lugar de descarga y horarios permitidos. Para patios y terrazas, revisá el espacio cubierto y el acceso a agua y electricidad.'],
    sections:[
      {title:'Contanos en qué zona celebrás',paragraphs:['Recibimos consultas para Asunción y Gran Asunción. La cobertura de cada solicitud se confirma con el proveedor según fecha, formato y dirección del evento.'],items:['Asunción','Luque y Mariano Roque Alonso','San Lorenzo y Fernando de la Mora','Lambaré y Villa Elisa','Capiatá y Ñemby']},
      {title:'Lo que cambia según el lugar',cards:[['Salón de eventos','Pedí las reglas de ingreso de proveedores, los horarios de montaje y qué equipamiento de cocina está disponible.'],['Oficina o edificio','Avisá si hay escaleras, ascensor de carga o controles de acceso. Reservá un sector para recibir y organizar las bandejas.'],['Casa o quincho','Revisá mesadas, puntos de electricidad y un lugar protegido para servir. Acordá una alternativa si el clima cambia.']]},
      {title:'Traslado y horarios en la cotización',paragraphs:['El traslado depende de la ubicación y del equipo necesario. Pedí que la propuesta indique si contempla descarga, espera, estacionamiento y retiro al finalizar el evento.','Compartí tanto la hora de llegada de los invitados como la del acceso al lugar. El montaje necesita su propio tiempo antes de comenzar a servir.']}
    ],faq:[['¿Trabajan en cualquier barrio de Asunción?','Podés enviar tu consulta indicando el barrio. Confirmamos la cobertura para esa dirección con el proveedor antes de avanzar.'],['¿Puedo consultar para Gran Asunción?','Sí. Indicá la ciudad y la zona para revisar disponibilidad y traslado; la cobertura no se confirma solo por completar la consulta.'],['¿El traslado se cobra por separado?','Depende del proveedor y del servicio. Solicitá que quede detallado en la propuesta, junto con montaje y retiro.'],['¿Se puede montar temprano en una oficina?','Consultá el horario requerido y las reglas del edificio. El proveedor debe confirmar si puede organizar la entrega y el montaje en esa franja.'],['¿Qué datos necesitan de un salón?','Nombre del espacio, zona, acceso de carga y equipamiento disponible. Podés compartir la dirección exacta durante la coordinación.'],['¿Qué hago si el evento es al aire libre?','Contanos si hay un sector cubierto y cómo se accede. Definí con el lugar y el proveedor una alternativa para lluvia o calor intenso.']],related:['catering','occ-bodas'],waMessage:'Hola, mi evento es en Asunción. ¿Me ayudás a consultar disponibilidad de catering?'},
  {id:'404',h1:'No encontramos esa página',intro:['Podés volver al inicio o explorar las opciones de catering para tu evento.'],related:['home','catering']}
];
