// Weekly reference prices from the official list (MAG, Dirección de Comercialización / SIMA).
// Generated by: node scripts/abasto-precios.mjs <csv>. Stays unpublished until Anton decides to
// publish prices (AGENTS.md rule 5 bans price numbers everywhere else on the site).
export default {
  published: false,
  source: '',
  verifiedAt: '',
  rows: [],
};
