// Single route manifest. P1a publishes four content routes and the 404.
export default [
  {
    "id": "home",
    "kind": "home",
    "path": "/",
    "label": "Inicio",
    "title": "Catering en Gran Asunción | comida.com.py",
    "meta": "Contanos qué celebrás y te ayudamos a consultar catering en Gran Asunción. Pedí tu presupuesto gratis y sin compromiso.",
    "indexable": true,
    "published": true,
    "parent": null,
    "updatedAt": "2026-09-19"
  },
  {
    "id": "catering",
    "kind": "hub",
    "path": "/catering/",
    "label": "Catering",
    "title": "Servicio de catering para eventos | comida.com.py",
    "meta": "Elegí el formato de catering para tu evento: bocaditos, buffet o menú servido. Consultá disponibilidad en Gran Asunción.",
    "indexable": true,
    "published": true,
    "parent": "home",
    "updatedAt": "2026-09-19"
  },
  {
    "id": "occ-eventos-empresariales",
    "kind": "occasion",
    "path": "/catering/eventos-empresariales/",
    "label": "Eventos empresariales",
    "title": "Eventos empresariales | comida.com.py",
    "meta": "Información de eventos empresariales en comida.com.py.",
    "indexable": true,
    "published": false,
    "parent": "catering",
    "updatedAt": "2026-09-19"
  },
  {
    "id": "occ-fin-de-ano",
    "kind": "occasion",
    "path": "/catering/fin-de-ano/",
    "label": "Fin de año",
    "title": "Fin de año | comida.com.py",
    "meta": "Información de fin de año en comida.com.py.",
    "indexable": true,
    "published": false,
    "parent": "catering",
    "updatedAt": "2026-09-19"
  },
  {
    "id": "occ-bodas",
    "kind": "occasion",
    "path": "/catering/bodas/",
    "label": "Bodas",
    "title": "Catering para bodas | comida.com.py",
    "meta": "Planeá el catering de tu boda: recepción, cena y servicio. Contanos tu fecha, lugar e invitados para consultar un presupuesto.",
    "indexable": true,
    "published": true,
    "parent": "catering",
    "updatedAt": "2026-09-19"
  },
  {
    "id": "occ-15-anos",
    "kind": "occasion",
    "path": "/catering/15-anos/",
    "label": "15 años",
    "title": "15 años | comida.com.py",
    "meta": "Información de 15 años en comida.com.py.",
    "indexable": true,
    "published": false,
    "parent": "catering",
    "updatedAt": "2026-09-19"
  },
  {
    "id": "occ-coffee-break",
    "kind": "occasion",
    "path": "/catering/coffee-break/",
    "label": "Coffee break",
    "title": "Coffee break | comida.com.py",
    "meta": "Información de coffee break en comida.com.py.",
    "indexable": true,
    "published": false,
    "parent": "catering",
    "updatedAt": "2026-09-19"
  },
  {
    "id": "occ-bocaditos",
    "kind": "occasion",
    "path": "/catering/bocaditos/",
    "label": "Bocaditos",
    "title": "Bocaditos | comida.com.py",
    "meta": "Información de bocaditos en comida.com.py.",
    "indexable": true,
    "published": false,
    "parent": "catering",
    "updatedAt": "2026-09-19"
  },
  {
    "id": "occ-cumpleanos",
    "kind": "occasion",
    "path": "/catering/cumpleanos/",
    "label": "Cumpleaños",
    "title": "Cumpleaños | comida.com.py",
    "meta": "Información de cumpleaños en comida.com.py.",
    "indexable": true,
    "published": false,
    "parent": "catering",
    "updatedAt": "2026-09-19"
  },
  {
    "id": "city-asuncion",
    "kind": "city",
    "path": "/catering/asuncion/",
    "label": "Asunción",
    "title": "Catering en Asunción | comida.com.py",
    "meta": "Organizá tu catering en Asunción: acceso al salón, horarios, montaje y traslado. Contanos tu zona y consultá disponibilidad.",
    "indexable": true,
    "published": true,
    "parent": "catering",
    "updatedAt": "2026-09-19"
  },
  {
    "id": "chef",
    "kind": "line",
    "path": "/chef-a-domicilio/",
    "label": "Chef a domicilio",
    "title": "Chef a domicilio | comida.com.py",
    "meta": "Información de chef a domicilio en comida.com.py.",
    "indexable": false,
    "published": false,
    "parent": "home",
    "updatedAt": "2026-09-19"
  },
  {
    "id": "precios",
    "kind": "precios",
    "path": "/precios/",
    "label": "Precios",
    "title": "Precios | comida.com.py",
    "meta": "Información de precios en comida.com.py.",
    "indexable": true,
    "published": false,
    "parent": "home",
    "updatedAt": "2026-09-19"
  },
  {
    "id": "presupuesto",
    "kind": "form",
    "path": "/presupuesto/",
    "label": "Presupuesto",
    "title": "Presupuesto | comida.com.py",
    "meta": "Información de presupuesto en comida.com.py.",
    "indexable": true,
    "published": false,
    "parent": "home",
    "updatedAt": "2026-09-19"
  },
  {
    "id": "como-funciona",
    "kind": "como-funciona",
    "path": "/como-funciona/",
    "label": "Cómo funciona",
    "title": "Cómo funciona | comida.com.py",
    "meta": "Información de cómo funciona en comida.com.py.",
    "indexable": true,
    "published": false,
    "parent": "home",
    "updatedAt": "2026-09-19"
  },
  {
    "id": "proveedores",
    "kind": "proveedores",
    "path": "/proveedores/",
    "label": "Proveedores",
    "title": "Proveedores | comida.com.py",
    "meta": "Información de proveedores en comida.com.py.",
    "indexable": true,
    "published": false,
    "parent": "home",
    "updatedAt": "2026-09-19"
  },
  {
    "id": "sobre",
    "kind": "sobre",
    "path": "/sobre/",
    "label": "Sobre nosotros",
    "title": "Sobre nosotros | comida.com.py",
    "meta": "Información de sobre nosotros en comida.com.py.",
    "indexable": true,
    "published": false,
    "parent": "home",
    "updatedAt": "2026-09-19"
  },
  {
    "id": "contacto",
    "kind": "contacto",
    "path": "/contacto/",
    "label": "Contacto",
    "title": "Contacto | comida.com.py",
    "meta": "Información de contacto en comida.com.py.",
    "indexable": true,
    "published": false,
    "parent": "home",
    "updatedAt": "2026-09-19"
  },
  {
    "id": "terminos",
    "kind": "terminos",
    "path": "/terminos/",
    "label": "Términos",
    "title": "Términos | comida.com.py",
    "meta": "Información de términos en comida.com.py.",
    "indexable": true,
    "published": false,
    "parent": "home",
    "updatedAt": "2026-09-19"
  },
  {
    "id": "privacidad",
    "kind": "privacidad",
    "path": "/privacidad/",
    "label": "Privacidad",
    "title": "Privacidad | comida.com.py",
    "meta": "Información de privacidad en comida.com.py.",
    "indexable": true,
    "published": false,
    "parent": "home",
    "updatedAt": "2026-09-19"
  },
  {
    "id": "gracias",
    "kind": "gracias",
    "path": "/gracias/",
    "label": "Gracias",
    "title": "Gracias | comida.com.py",
    "meta": "Información de gracias en comida.com.py.",
    "indexable": false,
    "published": false,
    "parent": "home",
    "updatedAt": "2026-09-19"
  },
  {
    "id": "404",
    "kind": "404",
    "path": "/404.html",
    "label": "Página no encontrada",
    "title": "Página no encontrada | comida.com.py",
    "meta": "Información de página no encontrada en comida.com.py.",
    "indexable": false,
    "published": true,
    "parent": "home",
    "updatedAt": "2026-09-19"
  }
];
