// Single route manifest: chef and gracias remain noindex; 404 is excluded from sitemap.
export default [
  {
    "id": "home",
    "kind": "home",
    "path": "/",
    "label": "Inicio",
    "title": "Catering en Gran Asunción | comida.com.py",
    "meta": "Contanos qué celebrás y te ayudamos a consultar catering en Gran Asunción. Pedí tu presupuesto gratis y sin compromiso.",
    "indexable": true,
    "published": true,
    "parent": null,
    "updatedAt": "2026-09-19"
  },
  {
    "id": "catering",
    "kind": "hub",
    "path": "/catering/",
    "label": "Catering",
    "title": "Servicio de catering para eventos | comida.com.py",
    "meta": "Elegí el formato de catering para tu evento: bocaditos, buffet o menú servido. Consultá disponibilidad en Gran Asunción.",
    "indexable": true,
    "published": true,
    "parent": "home",
    "updatedAt": "2026-09-19"
  },
  {
    "id": "occ-eventos-empresariales",
    "kind": "occasion",
    "path": "/catering/eventos-empresariales/",
    "label": "Eventos empresariales",
    "title": "Catering empresarial | comida.com.py",
    "meta": "Una reunión con clientes y una jornada de capacitación tienen ritmos diferentes.",
    "indexable": true,
    "published": true,
    "parent": "catering",
    "updatedAt": "2026-09-19"
  },
  {
    "id": "occ-fin-de-ano",
    "kind": "occasion",
    "path": "/catering/fin-de-ano/",
    "label": "Fin de año",
    "title": "Catering de fin de año | comida.com.py",
    "meta": "La despedida del año combina comida, brindis y momentos de reconocimiento.",
    "indexable": true,
    "published": true,
    "parent": "catering",
    "updatedAt": "2026-09-19"
  },
  {
    "id": "occ-bodas",
    "kind": "occasion",
    "path": "/catering/bodas/",
    "label": "Bodas",
    "title": "Catering para bodas | comida.com.py",
    "meta": "Planeá el catering de tu boda: recepción, cena y servicio. Contanos tu fecha, lugar e invitados para consultar un presupuesto.",
    "indexable": true,
    "published": true,
    "parent": "catering",
    "updatedAt": "2026-09-19"
  },
  {
    "id": "occ-15-anos",
    "kind": "occasion",
    "path": "/catering/15-anos/",
    "label": "15 años",
    "title": "Catering para 15 años | comida.com.py",
    "meta": "En una fiesta de quince, la recepción, la entrada y el baile marcan cuándo servir.",
    "indexable": true,
    "published": true,
    "parent": "catering",
    "updatedAt": "2026-09-19"
  },
  {
    "id": "occ-coffee-break",
    "kind": "occasion",
    "path": "/catering/coffee-break/",
    "label": "Coffee break",
    "title": "Coffee break para eventos | comida.com.py",
    "meta": "La pausa de una capacitación necesita ser fácil de encontrar y rápida de servir.",
    "indexable": true,
    "published": true,
    "parent": "catering",
    "updatedAt": "2026-09-19"
  },
  {
    "id": "occ-bocaditos",
    "kind": "occasion",
    "path": "/catering/bocaditos/",
    "label": "Bocaditos",
    "title": "Bocaditos salados y dulces | comida.com.py",
    "meta": "Los bocaditos pueden abrir una celebración o ser la comida principal de un encuentro.",
    "indexable": true,
    "published": true,
    "parent": "catering",
    "updatedAt": "2026-09-19"
  },
  {
    "id": "occ-cumpleanos",
    "kind": "occasion",
    "path": "/catering/cumpleanos/",
    "label": "Cumpleaños",
    "title": "Catering para cumpleaños | comida.com.py",
    "meta": "Un cumpleaños en casa necesita espacio para conversar, servir y compartir la torta.",
    "indexable": true,
    "published": true,
    "parent": "catering",
    "updatedAt": "2026-09-19"
  },
  {
    "id": "city-asuncion",
    "kind": "city",
    "path": "/catering/asuncion/",
    "label": "Asunción",
    "title": "Catering en Asunción | comida.com.py",
    "meta": "Organizá tu catering en Asunción: acceso al salón, horarios, montaje y traslado. Contanos tu zona y consultá disponibilidad.",
    "indexable": true,
    "published": true,
    "parent": "catering",
    "updatedAt": "2026-09-19"
  },
  {
    "id": "chef",
    "kind": "line",
    "path": "/chef-a-domicilio/",
    "label": "Chef a domicilio",
    "title": "Chef a domicilio: guía de consulta | comida.com.py",
    "meta": "Una comida preparada en tu casa empieza por conocer la cocina disponible y el tipo de encuentro que querés organizar.",
    "indexable": false,
    "published": true,
    "parent": "home",
    "updatedAt": "2026-09-19"
  },
  {
    "id": "precios",
    "kind": "precios",
    "path": "/precios/",
    "label": "Precios",
    "title": "Cuánto cuesta un catering | comida.com.py",
    "meta": "Antes de comparar presupuestos, definí qué comida y qué atención necesitás.",
    "indexable": true,
    "published": true,
    "parent": "home",
    "updatedAt": "2026-09-19"
  },
  {
    "id": "presupuesto",
    "kind": "form",
    "path": "/presupuesto/",
    "label": "Presupuesto",
    "title": "Pedí un presupuesto de catering | comida.com.py",
    "meta": "Contanos qué estás organizando, para cuándo y en qué zona.",
    "indexable": true,
    "published": true,
    "parent": "home",
    "updatedAt": "2026-09-19"
  },
  {
    "id": "como-funciona",
    "kind": "como-funciona",
    "path": "/como-funciona/",
    "label": "Cómo funciona",
    "title": "Cómo funciona la consulta de catering | comida.com.py",
    "meta": "Te ayudamos a ordenar el pedido y consultar opciones de catering para tu encuentro.",
    "indexable": true,
    "published": true,
    "parent": "home",
    "updatedAt": "2026-09-19"
  },
  {
    "id": "proveedores",
    "kind": "proveedores",
    "path": "/proveedores/",
    "label": "Proveedores",
    "title": "Presentá tu catering como proveedor | comida.com.py",
    "meta": "Si preparás catering y querés recibir consultas acordes a tu servicio, contanos tus formatos, zonas y capacidad de atención.",
    "indexable": true,
    "published": true,
    "parent": "home",
    "updatedAt": "2026-09-19"
  },
  {
    "id": "sobre",
    "kind": "sobre",
    "path": "/sobre/",
    "label": "Sobre nosotros",
    "title": "Sobre comida.com.py | comida.com.py",
    "meta": "comida.com.py nace para ayudar a definir qué pedir cuando organizás un evento en Gran Asunción.",
    "indexable": true,
    "published": true,
    "parent": "home",
    "updatedAt": "2026-09-19"
  },
  {
    "id": "contacto",
    "kind": "contacto",
    "path": "/contacto/",
    "label": "Contacto",
    "title": "Contacto para tu consulta de catering | comida.com.py",
    "meta": "Podés comunicarte por WhatsApp para consultar catering, ampliar un pedido o presentar tu servicio como proveedor.",
    "indexable": true,
    "published": true,
    "parent": "home",
    "updatedAt": "2026-09-19"
  },
  {
    "id": "terminos",
    "kind": "terminos",
    "path": "/terminos/",
    "label": "Términos",
    "title": "Condiciones del servicio de referencia | comida.com.py",
    "meta": "Estas condiciones explican el alcance de la orientación y coordinación ofrecidas por comida.com.py.",
    "indexable": true,
    "published": true,
    "parent": "home",
    "updatedAt": "2026-09-19"
  },
  {
    "id": "privacidad",
    "kind": "privacidad",
    "path": "/privacidad/",
    "label": "Privacidad",
    "title": "Privacidad de tus consultas | comida.com.py",
    "meta": "Para orientar un pedido necesitamos información de contacto y algunos datos del evento.",
    "indexable": true,
    "published": true,
    "parent": "home",
    "updatedAt": "2026-09-19"
  },
  {
    "id": "gracias",
    "kind": "gracias",
    "path": "/gracias/",
    "label": "Gracias",
    "title": "Estado de tu consulta | comida.com.py",
    "meta": "Llegar a esta página no confirma que una solicitud haya sido enviada o recibida.",
    "indexable": false,
    "published": true,
    "parent": "home",
    "updatedAt": "2026-09-19"
  },
  {
    "id": "404",
    "kind": "404",
    "path": "/404.html",
    "label": "Página no encontrada",
    "title": "Página no encontrada | comida.com.py",
    "meta": "Información de página no encontrada en comida.com.py.",
    "indexable": false,
    "published": true,
    "parent": "home",
    "updatedAt": "2026-09-19"
  }
];
