import {esc,attr} from '../engine/escape.mjs';
import {leadForm,providerForm} from './lead-form.mjs';
import {estimator} from './estimator.mjs';
// Where the primary CTA sends a visitor: the brief form, prefilled with the page's occasion when it has one.
export function briefHref(route,page){const occasion=page.formOccasion||(route.kind==='occasion'?route.id.replace(/^occ-/,''):'');return '/presupuesto/'+(occasion?'?ocasion='+encodeURIComponent(occasion):'')}
export function renderContent(context,kind){
  const {page,route,picture,routes,wa,config}=context;
  if(!page?.h1)throw Error(`Missing copy for ${route.id}; keep this route unpublished.`);
  const section=s=>`<section${s.id?` id="${attr(s.id)}"`:''}><h2>${esc(s.title)}</h2>${(s.paragraphs||[]).map(p=>`<p class="intro">${esc(p)}</p>`).join('')}${s.items?`<ul>${s.items.map(i=>`<li>${esc(i)}</li>`).join('')}</ul>`:''}${s.cards?`<div class="content-grid">${s.cards.map(([h,p])=>`<article class="content-card"><h3>${esc(h)}</h3><p>${esc(p)}</p></article>`).join('')}</div>`:''}${s.html||''}</section>`;
  const hasForm=page.form==='lead'||page.form==='provider';
  const form=page.form==='lead'?`<section class="page-form" id="formulario" aria-labelledby="lf-h">${leadForm({routes,config,wa,source:route.path,waMessage:page.waMessage,heading:page.formHeading,extraOccasions:page.formExtraOccasions})}</section>`:page.form==='provider'?`<section class="page-form" id="formulario" aria-labelledby="pf-h">${providerForm({config,wa,source:route.path,waMessage:page.waMessage})}</section>`:'';
  const cta=kind==='404'||page.formFirst?'':hasForm?`<div class="cta-row"><a class="btn btn-primary" href="#formulario">${page.form==='provider'?'Completar la presentación':'Completar la solicitud'}</a><a class="btn btn-ghost" href="${attr(wa(page.waMessage))}">Escribinos por WhatsApp</a></div>`:`<div class="cta-row"><a class="btn btn-primary" href="${attr(briefHref(route,page))}">${esc(page.ctaLabel||'Pedí tu presupuesto')}</a><a class="btn btn-ghost" href="${attr(wa(page.waMessage))}">Escribinos por WhatsApp</a></div>`;
  const notice=page.notice?`<div class="notice" data-show-when="${attr(page.notice.when)}" hidden><h2>${esc(page.notice.title)}</h2><p>${esc(page.notice.text)}</p></div>`:'';
  const source=page.source?`<p class="source-line">Fuente: ${esc(page.source)} · Revisado: <time datetime="${attr(page.verifiedAt)}">${esc(formatDate(page.verifiedAt))}</time></p>`:'';
  return `<main id="top" class="content-page"><div class="wrap">${breadcrumbs(route,routes)}<h1>${esc(page.h1)}</h1>${notice}${(page.intro||[]).map(p=>`<p class="intro">${esc(p)}</p>`).join('')}${cta}${page.image?`<figure class="page-image">${picture(page.image,'(min-width:900px) 1200px, 100vw',true)}<figcaption class="cap">Imagen ilustrativa</figcaption></figure>`:''}${page.formFirst?form:''}${kind==='precios'?estimator(context):''}${(page.sections||[]).map(section).join('')}${page.formFirst?'':form}${source}${kind==='404'||page.noProcess?'':`<section data-shared="process"><h2>Cómo seguimos tu consulta</h2><ol class="steps"><li><h3>Contanos tu evento</h3><p>Indicá fecha, zona y cantidad de personas.</p></li><li><h3>Consultamos disponibilidad</h3><p>Revisamos tu solicitud en nuestro horario de atención.</p></li><li><h3>Elegí con el alcance claro</h3><p>Contratás y coordinás el servicio directamente con el proveedor.</p></li></ol></section>`}${page.faq?`<section class="faq"><h2>${esc(page.faqTitle||'Preguntas sobre '+route.label.toLowerCase())}</h2>${page.faq.map(([q,a])=>`<details><summary>${esc(q)}</summary><p>${esc(a)}</p></details>`).join('')}</section>`:''}${relatedBlock(page,routes)}</div></main>`;
}
function relatedBlock(page,routes){const links=(page.related||[]).map(id=>{const r=routes.find(r=>r.id===id&&r.published);if(!r)throw Error('Unpublished related route: '+id);return r}).filter(r=>r.indexable||page.allowNoindexLinks);return links.length?`<section><h2>Seguí explorando</h2><div class="related">${links.map(r=>`<a href="${attr(r.path)}">${esc(r.label)}</a>`).join('')}</div></section>`:''}
const MONTHS=['enero','febrero','marzo','abril','mayo','junio','julio','agosto','septiembre','octubre','noviembre','diciembre'];
function formatDate(iso){const [y,m,d]=String(iso).split('-').map(Number);return `${d} de ${MONTHS[m-1]} de ${y}`}
export function breadcrumbs(route,routes){let chain=[],r=route;while(r){chain.unshift(r);r=routes.find(p=>p.id===r.parent)}return `<nav class="breadcrumbs" aria-label="Ruta de navegación"><ol>${chain.map(r=>`<li>${r.id===route.id?`<span aria-current="page">${esc(r.label)}</span>`:`<a href="${attr(r.path)}">${esc(r.label)}</a>`}</li>`).join('')}</ol></nav>`}
