// Import the weekly official reference prices into sites/comida/abasto-precios.mjs (idea 11).
// Input: a CSV with columns producto,unidad,minimo,maximo (copy the MAG/SIMA weekly list into a sheet and
// export it). Prices are written as text exactly as given (e.g. "8.000 Gs"). The page stays unpublished
// until you pass --publish, which you should only do after deciding to allow prices (AGENTS.md rule 5).
//   node scripts/abasto-precios.mjs precios.csv --source "MAG, Dirección de Comercialización (SIMA), lista del 2026-09-22" [--publish]
import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const args=process.argv.slice(2),file=args.find(a=>!a.startsWith('--')&&!args[args.indexOf(a)-1]?.startsWith('--source'));
const source=args[args.indexOf('--source')+1];
if(!file||!fs.existsSync(file)||args.indexOf('--source')<0||!source){console.error('Usage: node scripts/abasto-precios.mjs <csv> --source "<official source and list date>" [--publish]');process.exit(2)}
const lines=fs.readFileSync(file,'utf8').replace(/^﻿/,'').split(/\r?\n/).filter(Boolean);
const head=lines.shift().toLowerCase().split(',').map(s=>s.trim());
const idx=k=>head.indexOf(k);
if(['producto','unidad','minimo','maximo'].some(k=>idx(k)<0)){console.error('CSV needs columns: producto,unidad,minimo,maximo');process.exit(1)}
const rows=lines.map(l=>l.split(',').map(s=>s.trim())).filter(c=>c[idx('producto')]).map(c=>({producto:c[idx('producto')],unidad:c[idx('unidad')],minimo:c[idx('minimo')],maximo:c[idx('maximo')]}));
const today=new Date().toISOString().slice(0,10);
const out=`// Weekly reference prices from the official list. Generated by scripts/abasto-precios.mjs on ${today}.\nexport default ${JSON.stringify({published:args.includes('--publish'),source,verifiedAt:today,rows},null,2)};\n`;
fs.writeFileSync(path.join(root,'sites/comida/abasto-precios.mjs'),out);
console.log(`Wrote ${rows.length} rows (published: ${args.includes('--publish')}). Build and verify next.`);
